using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using Rfid.Helpers;
using Rfid.Helpers.PageHelpers;
using Rfid.Models;

namespace Rfid
{
    /// <summary>
    /// Interaction logic for UserInfo_FindResult.xaml
    /// </summary>
    public partial class FindResultPage
    {
        public FindResultPage()
        {
            InitializeComponent();
        }

        private readonly FindResultHelper _findResultHelper = new FindResultHelper();
        public int SelectedId { get; private set; }
        public M_Users SelectedUser { get; private set; }

        public FindResultPage(UserFinderHelper find )
        {
            InitializeComponent();

            _findResultHelper.Initialize(GridBasicInformation, find);
        }

        private void StackPanel_MouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            dynamic s = GridBasicInformation.CurrentCell.Item;
            if (s == DependencyProperty.UnsetValue)
            {
                MessageBox.Show((string)Application.Current.Resources[StringsMapper.ErrorUserNSel], (string)Application.Current.Resources[StringsMapper.ErrorHeader], MessageBoxButton.OK, MessageBoxImage.Exclamation);
            }
            else
            {
                int id = s.Id;
                var p = new AboutUserPage(id);
                this.NavigationService.Navigate(p);
            }
        }

        private void GridBasicInformation_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (GridBasicInformation.SelectedIndex == -1)
            {
                return;
            }

            dynamic s = GridBasicInformation.CurrentCell.Item;
            SelectedId = s.Id;

            SelectedUser = _findResultHelper.GetUserInfo(SelectedId, NameUser, imageReport);

        }

        private void Page_Loaded(object sender, RoutedEventArgs e)
        {
            NameUser.Text = Application.Current.Resources[StringsMapper.FirstName] +
               " " + Application.Current.Resources[StringsMapper.SecondName];
            Singelton.MainWindow.ChangeStringAddres(Title);
        }

        private void GridBasicInformation_AutoGeneratedColumns(object sender, EventArgs e)
        {
            GridBasicInformation.Columns[1].Header = Application.Current.Resources[StringsMapper.FirstName];
            GridBasicInformation.Columns[2].Header = Application.Current.Resources[StringsMapper.SecondName];
            GridBasicInformation.Columns[3].Header = Application.Current.Resources[StringsMapper.ThirdName];
            GridBasicInformation.Columns[4].Header = Application.Current.Resources[StringsMapper.DepartmentInfo];
            GridBasicInformation.Columns[5].Header = Application.Current.Resources[StringsMapper.StartTime];
            GridBasicInformation.Columns[6].Header = Application.Current.Resources[StringsMapper.EndTime];
            GridBasicInformation.Columns[7].Header = Application.Current.Resources[StringsMapper.TimeLate];
            GridBasicInformation.Columns[8].Header = Application.Current.Resources[StringsMapper.DinnerTime];
            GridBasicInformation.Columns[9].Header = Application.Current.Resources[StringsMapper.Phone];

        }
    }
}
